// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RxControlTopic.proto

package rx_msg;

public final class RxControlTopic {
  private RxControlTopic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReceiverRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 appID = 1;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    boolean hasAppID();
    /**
     * <code>optional int32 appID = 1;</code>
     */
    int getAppID();
  }
  /**
   * Protobuf type {@code rx_msg.ReceiverRequest}
   */
  public static final class ReceiverRequest extends
      com.google.protobuf.GeneratedMessage
      implements ReceiverRequestOrBuilder {
    // Use ReceiverRequest.newBuilder() to construct.
    private ReceiverRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReceiverRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReceiverRequest defaultInstance;
    public static ReceiverRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ReceiverRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReceiverRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              appID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rx_msg.RxControlTopic.ReceiverRequest.class, rx_msg.RxControlTopic.ReceiverRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ReceiverRequest> PARSER =
        new com.google.protobuf.AbstractParser<ReceiverRequest>() {
      public ReceiverRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReceiverRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReceiverRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 appID = 1;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appID_;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public int getAppID() {
      return appID_;
    }

    private void initFields() {
      appID_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, appID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, appID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rx_msg.RxControlTopic.ReceiverRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rx_msg.ReceiverRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rx_msg.RxControlTopic.ReceiverRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rx_msg.RxControlTopic.ReceiverRequest.class, rx_msg.RxControlTopic.ReceiverRequest.Builder.class);
      }

      // Construct using rx_msg.RxControlTopic.ReceiverRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRequest_descriptor;
      }

      public rx_msg.RxControlTopic.ReceiverRequest getDefaultInstanceForType() {
        return rx_msg.RxControlTopic.ReceiverRequest.getDefaultInstance();
      }

      public rx_msg.RxControlTopic.ReceiverRequest build() {
        rx_msg.RxControlTopic.ReceiverRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rx_msg.RxControlTopic.ReceiverRequest buildPartial() {
        rx_msg.RxControlTopic.ReceiverRequest result = new rx_msg.RxControlTopic.ReceiverRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appID_ = appID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rx_msg.RxControlTopic.ReceiverRequest) {
          return mergeFrom((rx_msg.RxControlTopic.ReceiverRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rx_msg.RxControlTopic.ReceiverRequest other) {
        if (other == rx_msg.RxControlTopic.ReceiverRequest.getDefaultInstance()) return this;
        if (other.hasAppID()) {
          setAppID(other.getAppID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rx_msg.RxControlTopic.ReceiverRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rx_msg.RxControlTopic.ReceiverRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 appID = 1;
      private int appID_ ;
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public int getAppID() {
        return appID_;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder setAppID(int value) {
        bitField0_ |= 0x00000001;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appID_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rx_msg.ReceiverRequest)
    }

    static {
      defaultInstance = new ReceiverRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rx_msg.ReceiverRequest)
  }

  public interface ReceiverReleaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 appID = 1;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    boolean hasAppID();
    /**
     * <code>optional int32 appID = 1;</code>
     */
    int getAppID();

    // optional int32 channel = 2;
    /**
     * <code>optional int32 channel = 2;</code>
     */
    boolean hasChannel();
    /**
     * <code>optional int32 channel = 2;</code>
     */
    int getChannel();
  }
  /**
   * Protobuf type {@code rx_msg.ReceiverRelease}
   */
  public static final class ReceiverRelease extends
      com.google.protobuf.GeneratedMessage
      implements ReceiverReleaseOrBuilder {
    // Use ReceiverRelease.newBuilder() to construct.
    private ReceiverRelease(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReceiverRelease(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReceiverRelease defaultInstance;
    public static ReceiverRelease getDefaultInstance() {
      return defaultInstance;
    }

    public ReceiverRelease getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReceiverRelease(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              appID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRelease_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRelease_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rx_msg.RxControlTopic.ReceiverRelease.class, rx_msg.RxControlTopic.ReceiverRelease.Builder.class);
    }

    public static com.google.protobuf.Parser<ReceiverRelease> PARSER =
        new com.google.protobuf.AbstractParser<ReceiverRelease>() {
      public ReceiverRelease parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReceiverRelease(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReceiverRelease> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 appID = 1;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appID_;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public int getAppID() {
      return appID_;
    }

    // optional int32 channel = 2;
    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <code>optional int32 channel = 2;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 channel = 2;</code>
     */
    public int getChannel() {
      return channel_;
    }

    private void initFields() {
      appID_ = 0;
      channel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, appID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, channel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, appID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverRelease parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rx_msg.RxControlTopic.ReceiverRelease prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rx_msg.ReceiverRelease}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rx_msg.RxControlTopic.ReceiverReleaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRelease_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRelease_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rx_msg.RxControlTopic.ReceiverRelease.class, rx_msg.RxControlTopic.ReceiverRelease.Builder.class);
      }

      // Construct using rx_msg.RxControlTopic.ReceiverRelease.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverRelease_descriptor;
      }

      public rx_msg.RxControlTopic.ReceiverRelease getDefaultInstanceForType() {
        return rx_msg.RxControlTopic.ReceiverRelease.getDefaultInstance();
      }

      public rx_msg.RxControlTopic.ReceiverRelease build() {
        rx_msg.RxControlTopic.ReceiverRelease result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rx_msg.RxControlTopic.ReceiverRelease buildPartial() {
        rx_msg.RxControlTopic.ReceiverRelease result = new rx_msg.RxControlTopic.ReceiverRelease(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appID_ = appID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rx_msg.RxControlTopic.ReceiverRelease) {
          return mergeFrom((rx_msg.RxControlTopic.ReceiverRelease)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rx_msg.RxControlTopic.ReceiverRelease other) {
        if (other == rx_msg.RxControlTopic.ReceiverRelease.getDefaultInstance()) return this;
        if (other.hasAppID()) {
          setAppID(other.getAppID());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rx_msg.RxControlTopic.ReceiverRelease parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rx_msg.RxControlTopic.ReceiverRelease) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 appID = 1;
      private int appID_ ;
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public int getAppID() {
        return appID_;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder setAppID(int value) {
        bitField0_ |= 0x00000001;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 channel = 2;
      private int channel_ ;
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rx_msg.ReceiverRelease)
    }

    static {
      defaultInstance = new ReceiverRelease(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rx_msg.ReceiverRelease)
  }

  public interface ReceiverAcquiredOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 appID = 1;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    boolean hasAppID();
    /**
     * <code>optional int32 appID = 1;</code>
     */
    int getAppID();

    // optional int32 channel = 2;
    /**
     * <code>optional int32 channel = 2;</code>
     */
    boolean hasChannel();
    /**
     * <code>optional int32 channel = 2;</code>
     */
    int getChannel();
  }
  /**
   * Protobuf type {@code rx_msg.ReceiverAcquired}
   */
  public static final class ReceiverAcquired extends
      com.google.protobuf.GeneratedMessage
      implements ReceiverAcquiredOrBuilder {
    // Use ReceiverAcquired.newBuilder() to construct.
    private ReceiverAcquired(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReceiverAcquired(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReceiverAcquired defaultInstance;
    public static ReceiverAcquired getDefaultInstance() {
      return defaultInstance;
    }

    public ReceiverAcquired getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReceiverAcquired(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              appID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverAcquired_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverAcquired_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rx_msg.RxControlTopic.ReceiverAcquired.class, rx_msg.RxControlTopic.ReceiverAcquired.Builder.class);
    }

    public static com.google.protobuf.Parser<ReceiverAcquired> PARSER =
        new com.google.protobuf.AbstractParser<ReceiverAcquired>() {
      public ReceiverAcquired parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReceiverAcquired(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReceiverAcquired> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 appID = 1;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appID_;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public int getAppID() {
      return appID_;
    }

    // optional int32 channel = 2;
    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <code>optional int32 channel = 2;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 channel = 2;</code>
     */
    public int getChannel() {
      return channel_;
    }

    private void initFields() {
      appID_ = 0;
      channel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, appID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, channel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, appID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverAcquired parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rx_msg.RxControlTopic.ReceiverAcquired prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rx_msg.ReceiverAcquired}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rx_msg.RxControlTopic.ReceiverAcquiredOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverAcquired_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverAcquired_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rx_msg.RxControlTopic.ReceiverAcquired.class, rx_msg.RxControlTopic.ReceiverAcquired.Builder.class);
      }

      // Construct using rx_msg.RxControlTopic.ReceiverAcquired.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverAcquired_descriptor;
      }

      public rx_msg.RxControlTopic.ReceiverAcquired getDefaultInstanceForType() {
        return rx_msg.RxControlTopic.ReceiverAcquired.getDefaultInstance();
      }

      public rx_msg.RxControlTopic.ReceiverAcquired build() {
        rx_msg.RxControlTopic.ReceiverAcquired result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rx_msg.RxControlTopic.ReceiverAcquired buildPartial() {
        rx_msg.RxControlTopic.ReceiverAcquired result = new rx_msg.RxControlTopic.ReceiverAcquired(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appID_ = appID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rx_msg.RxControlTopic.ReceiverAcquired) {
          return mergeFrom((rx_msg.RxControlTopic.ReceiverAcquired)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rx_msg.RxControlTopic.ReceiverAcquired other) {
        if (other == rx_msg.RxControlTopic.ReceiverAcquired.getDefaultInstance()) return this;
        if (other.hasAppID()) {
          setAppID(other.getAppID());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rx_msg.RxControlTopic.ReceiverAcquired parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rx_msg.RxControlTopic.ReceiverAcquired) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 appID = 1;
      private int appID_ ;
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public int getAppID() {
        return appID_;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder setAppID(int value) {
        bitField0_ |= 0x00000001;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 channel = 2;
      private int channel_ ;
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rx_msg.ReceiverAcquired)
    }

    static {
      defaultInstance = new ReceiverAcquired(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rx_msg.ReceiverAcquired)
  }

  public interface ReceiverReleasedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 appID = 1;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    boolean hasAppID();
    /**
     * <code>optional int32 appID = 1;</code>
     */
    int getAppID();

    // optional int32 channel = 2;
    /**
     * <code>optional int32 channel = 2;</code>
     */
    boolean hasChannel();
    /**
     * <code>optional int32 channel = 2;</code>
     */
    int getChannel();
  }
  /**
   * Protobuf type {@code rx_msg.ReceiverReleased}
   */
  public static final class ReceiverReleased extends
      com.google.protobuf.GeneratedMessage
      implements ReceiverReleasedOrBuilder {
    // Use ReceiverReleased.newBuilder() to construct.
    private ReceiverReleased(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReceiverReleased(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReceiverReleased defaultInstance;
    public static ReceiverReleased getDefaultInstance() {
      return defaultInstance;
    }

    public ReceiverReleased getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReceiverReleased(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              appID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverReleased_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverReleased_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rx_msg.RxControlTopic.ReceiverReleased.class, rx_msg.RxControlTopic.ReceiverReleased.Builder.class);
    }

    public static com.google.protobuf.Parser<ReceiverReleased> PARSER =
        new com.google.protobuf.AbstractParser<ReceiverReleased>() {
      public ReceiverReleased parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReceiverReleased(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReceiverReleased> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 appID = 1;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appID_;
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 appID = 1;</code>
     */
    public int getAppID() {
      return appID_;
    }

    // optional int32 channel = 2;
    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <code>optional int32 channel = 2;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 channel = 2;</code>
     */
    public int getChannel() {
      return channel_;
    }

    private void initFields() {
      appID_ = 0;
      channel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, appID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, channel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, appID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rx_msg.RxControlTopic.ReceiverReleased parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rx_msg.RxControlTopic.ReceiverReleased prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rx_msg.ReceiverReleased}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rx_msg.RxControlTopic.ReceiverReleasedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverReleased_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverReleased_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rx_msg.RxControlTopic.ReceiverReleased.class, rx_msg.RxControlTopic.ReceiverReleased.Builder.class);
      }

      // Construct using rx_msg.RxControlTopic.ReceiverReleased.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rx_msg.RxControlTopic.internal_static_rx_msg_ReceiverReleased_descriptor;
      }

      public rx_msg.RxControlTopic.ReceiverReleased getDefaultInstanceForType() {
        return rx_msg.RxControlTopic.ReceiverReleased.getDefaultInstance();
      }

      public rx_msg.RxControlTopic.ReceiverReleased build() {
        rx_msg.RxControlTopic.ReceiverReleased result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rx_msg.RxControlTopic.ReceiverReleased buildPartial() {
        rx_msg.RxControlTopic.ReceiverReleased result = new rx_msg.RxControlTopic.ReceiverReleased(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appID_ = appID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rx_msg.RxControlTopic.ReceiverReleased) {
          return mergeFrom((rx_msg.RxControlTopic.ReceiverReleased)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rx_msg.RxControlTopic.ReceiverReleased other) {
        if (other == rx_msg.RxControlTopic.ReceiverReleased.getDefaultInstance()) return this;
        if (other.hasAppID()) {
          setAppID(other.getAppID());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rx_msg.RxControlTopic.ReceiverReleased parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rx_msg.RxControlTopic.ReceiverReleased) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 appID = 1;
      private int appID_ ;
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public int getAppID() {
        return appID_;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder setAppID(int value) {
        bitField0_ |= 0x00000001;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 appID = 1;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 channel = 2;
      private int channel_ ;
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 channel = 2;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rx_msg.ReceiverReleased)
    }

    static {
      defaultInstance = new ReceiverReleased(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rx_msg.ReceiverReleased)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rx_msg_ReceiverRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rx_msg_ReceiverRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rx_msg_ReceiverRelease_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rx_msg_ReceiverRelease_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rx_msg_ReceiverAcquired_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rx_msg_ReceiverAcquired_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rx_msg_ReceiverReleased_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rx_msg_ReceiverReleased_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RxControlTopic.proto\022\006rx_msg\" \n\017Receiv" +
      "erRequest\022\r\n\005appID\030\001 \001(\005\"1\n\017ReceiverRele" +
      "ase\022\r\n\005appID\030\001 \001(\005\022\017\n\007channel\030\002 \001(\005\"2\n\020R" +
      "eceiverAcquired\022\r\n\005appID\030\001 \001(\005\022\017\n\007channe" +
      "l\030\002 \001(\005\"2\n\020ReceiverReleased\022\r\n\005appID\030\001 \001" +
      "(\005\022\017\n\007channel\030\002 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rx_msg_ReceiverRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rx_msg_ReceiverRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rx_msg_ReceiverRequest_descriptor,
              new java.lang.String[] { "AppID", });
          internal_static_rx_msg_ReceiverRelease_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rx_msg_ReceiverRelease_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rx_msg_ReceiverRelease_descriptor,
              new java.lang.String[] { "AppID", "Channel", });
          internal_static_rx_msg_ReceiverAcquired_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_rx_msg_ReceiverAcquired_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rx_msg_ReceiverAcquired_descriptor,
              new java.lang.String[] { "AppID", "Channel", });
          internal_static_rx_msg_ReceiverReleased_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_rx_msg_ReceiverReleased_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rx_msg_ReceiverReleased_descriptor,
              new java.lang.String[] { "AppID", "Channel", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
