all:
	protoc $(wildcard *.proto) --python_out=./../py --proto_path=/apps/site-packages/control/messages/proto --proto_path=.
py:
	protoc $(wildcard *.proto) --python_out=./../py --proto_path=/apps/site-packages/control/messages/proto/ --proto_path=.
