# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GalileoMessages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GalileoMessages.proto',
  package='galileo_msg',
  serialized_pb='\n\x15GalileoMessages.proto\x12\x0bgalileo_msg\"X\n\x07\x43luster\x12\x18\n\x07msgName\x18\x01 \x01(\t:\x07\x43LUSTER\x12\x13\n\x0bincomingCID\x18\x02 \x01(\x05\x12\r\n\x05label\x18\x03 \x01(\x05\x12\x0f\n\x07indices\x18\x04 \x03(\x05\"\x8b\x02\n\x10ProcessorResults\x12\"\n\x07msgName\x18\x01 \x01(\t:\x11PROCESSOR_RESULTS\x12\x16\n\x0eprocInstanceID\x18\x02 \x01(\t\x12\x10\n\x08metaFile\x18\x03 \x01(\t\x12\x13\n\x0bIQIndexFile\x18\x04 \x01(\t\x12\x14\n\x0csubGraphFile\x18\x05 \x01(\t\x12.\n\x10incomingClusters\x18\x06 \x03(\x0b\x32\x14.galileo_msg.Cluster\x12\x15\n\rcycloDisabled\x18\x07 \x01(\x08\x12\x0f\n\x07timeRes\x18\x08 \x01(\x01\x12\x0f\n\x07\x66reqRes\x18\t \x01(\x01\x12\x15\n\rsegmenterName\x18\n \x01(\t\"z\n\x0e\x43lusterMapping\x12 \n\x07msgName\x18\x01 \x01(\t:\x0f\x43LUSTER_MAPPING\x12\x16\n\x0bincomingCID\x18\x02 \x01(\x05:\x01\x30\x12\x13\n\tclusterID\x18\x03 \x01(\t:\x00\x12\x19\n\nnewCluster\x18\x04 \x01(\x08:\x05\x66\x61lse\"\x81\x01\n\x11\x41ggregatorResults\x12#\n\x07msgName\x18\x01 \x01(\t:\x12\x41GGREGATOR_RESULTS\x12/\n\nclusterMap\x18\x02 \x03(\x0b\x32\x1b.galileo_msg.ClusterMapping\x12\x16\n\x0eprocInstanceID\x18\x03 \x01(\t\"|\n\x0cLearnEmitter\x12\x1e\n\x07msgName\x18\x01 \x01(\t:\rLEARN_EMITTER\x12\x13\n\tclusterID\x18\x02 \x01(\t:\x00\x12\x1c\n\x0b\x65mitterName\x18\x03 \x01(\t:\x07\x44\x45\x46\x41ULT\x12\x19\n\x0b\x64\x65signation\x18\x04 \x01(\t:\x04gray\"Z\n\x10\x41ggregatorStatus\x12\"\n\x07msgName\x18\x01 \x01(\t:\x11\x41GGREGATOR_STATUS\x12\x12\n\nshouldExit\x18\x02 \x01(\x08\x12\x0e\n\x06\x65xited\x18\x03 \x01(\x08\"Z\n\x0f\x41ggregatorClear\x12!\n\x07msgName\x18\x01 \x01(\t:\x10\x41GGREGATOR_CLEAR\x12\x13\n\x0bshouldClear\x18\x02 \x01(\x08\x12\x0f\n\x07\x63leared\x18\x03 \x01(\x08\x42\x15\n\x13\x66v.protos.kepsvisor')




_CLUSTER = _descriptor.Descriptor(
  name='Cluster',
  full_name='galileo_msg.Cluster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='galileo_msg.Cluster.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("CLUSTER", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incomingCID', full_name='galileo_msg.Cluster.incomingCID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='galileo_msg.Cluster.label', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='indices', full_name='galileo_msg.Cluster.indices', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=126,
)


_PROCESSORRESULTS = _descriptor.Descriptor(
  name='ProcessorResults',
  full_name='galileo_msg.ProcessorResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='galileo_msg.ProcessorResults.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("PROCESSOR_RESULTS", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='procInstanceID', full_name='galileo_msg.ProcessorResults.procInstanceID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metaFile', full_name='galileo_msg.ProcessorResults.metaFile', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IQIndexFile', full_name='galileo_msg.ProcessorResults.IQIndexFile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subGraphFile', full_name='galileo_msg.ProcessorResults.subGraphFile', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incomingClusters', full_name='galileo_msg.ProcessorResults.incomingClusters', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cycloDisabled', full_name='galileo_msg.ProcessorResults.cycloDisabled', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeRes', full_name='galileo_msg.ProcessorResults.timeRes', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='freqRes', full_name='galileo_msg.ProcessorResults.freqRes', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segmenterName', full_name='galileo_msg.ProcessorResults.segmenterName', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=396,
)


_CLUSTERMAPPING = _descriptor.Descriptor(
  name='ClusterMapping',
  full_name='galileo_msg.ClusterMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='galileo_msg.ClusterMapping.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("CLUSTER_MAPPING", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incomingCID', full_name='galileo_msg.ClusterMapping.incomingCID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clusterID', full_name='galileo_msg.ClusterMapping.clusterID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newCluster', full_name='galileo_msg.ClusterMapping.newCluster', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=398,
  serialized_end=520,
)


_AGGREGATORRESULTS = _descriptor.Descriptor(
  name='AggregatorResults',
  full_name='galileo_msg.AggregatorResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='galileo_msg.AggregatorResults.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("AGGREGATOR_RESULTS", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clusterMap', full_name='galileo_msg.AggregatorResults.clusterMap', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='procInstanceID', full_name='galileo_msg.AggregatorResults.procInstanceID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=523,
  serialized_end=652,
)


_LEARNEMITTER = _descriptor.Descriptor(
  name='LearnEmitter',
  full_name='galileo_msg.LearnEmitter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='galileo_msg.LearnEmitter.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("LEARN_EMITTER", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clusterID', full_name='galileo_msg.LearnEmitter.clusterID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emitterName', full_name='galileo_msg.LearnEmitter.emitterName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("DEFAULT", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='designation', full_name='galileo_msg.LearnEmitter.designation', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("gray", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=654,
  serialized_end=778,
)


_AGGREGATORSTATUS = _descriptor.Descriptor(
  name='AggregatorStatus',
  full_name='galileo_msg.AggregatorStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='galileo_msg.AggregatorStatus.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("AGGREGATOR_STATUS", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shouldExit', full_name='galileo_msg.AggregatorStatus.shouldExit', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exited', full_name='galileo_msg.AggregatorStatus.exited', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=780,
  serialized_end=870,
)


_AGGREGATORCLEAR = _descriptor.Descriptor(
  name='AggregatorClear',
  full_name='galileo_msg.AggregatorClear',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='galileo_msg.AggregatorClear.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("AGGREGATOR_CLEAR", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shouldClear', full_name='galileo_msg.AggregatorClear.shouldClear', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cleared', full_name='galileo_msg.AggregatorClear.cleared', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=872,
  serialized_end=962,
)

_PROCESSORRESULTS.fields_by_name['incomingClusters'].message_type = _CLUSTER
_AGGREGATORRESULTS.fields_by_name['clusterMap'].message_type = _CLUSTERMAPPING
DESCRIPTOR.message_types_by_name['Cluster'] = _CLUSTER
DESCRIPTOR.message_types_by_name['ProcessorResults'] = _PROCESSORRESULTS
DESCRIPTOR.message_types_by_name['ClusterMapping'] = _CLUSTERMAPPING
DESCRIPTOR.message_types_by_name['AggregatorResults'] = _AGGREGATORRESULTS
DESCRIPTOR.message_types_by_name['LearnEmitter'] = _LEARNEMITTER
DESCRIPTOR.message_types_by_name['AggregatorStatus'] = _AGGREGATORSTATUS
DESCRIPTOR.message_types_by_name['AggregatorClear'] = _AGGREGATORCLEAR

class Cluster(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLUSTER

  # @@protoc_insertion_point(class_scope:galileo_msg.Cluster)

class ProcessorResults(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROCESSORRESULTS

  # @@protoc_insertion_point(class_scope:galileo_msg.ProcessorResults)

class ClusterMapping(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLUSTERMAPPING

  # @@protoc_insertion_point(class_scope:galileo_msg.ClusterMapping)

class AggregatorResults(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AGGREGATORRESULTS

  # @@protoc_insertion_point(class_scope:galileo_msg.AggregatorResults)

class LearnEmitter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEARNEMITTER

  # @@protoc_insertion_point(class_scope:galileo_msg.LearnEmitter)

class AggregatorStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AGGREGATORSTATUS

  # @@protoc_insertion_point(class_scope:galileo_msg.AggregatorStatus)

class AggregatorClear(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AGGREGATORCLEAR

  # @@protoc_insertion_point(class_scope:galileo_msg.AggregatorClear)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023fv.protos.kepsvisor')
# @@protoc_insertion_point(module_scope)
