# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProMachinaMessages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProMachinaMessages.proto',
  package='fv.tb.protos.PMProtos',
  serialized_pb='\n\x18ProMachinaMessages.proto\x12\x15\x66v.tb.protos.PMProtos\"\xd4\x02\n\x07PMFrame\x12\x18\n\x07msgName\x18\x01 \x01(\t:\x07PMFRAME\x12\x11\n\ttoAddress\x18\x02 \x01(\x05\x12\x13\n\x0b\x66romAddress\x18\x03 \x01(\x05\x12\x12\n\ncountValue\x18\x04 \x01(\x05\x12\x15\n\rframeFormatID\x18\x05 \x01(\t\x12\x0f\n\x07trackID\x18\x06 \x01(\t\x12\x11\n\ttrackType\x18\x07 \x01(\t\x12\x0c\n\x04posX\x18\x08 \x01(\x01\x12\x0c\n\x04posY\x18\t \x01(\x01\x12\x0c\n\x04posZ\x18\n \x01(\x01\x12\x0c\n\x04velX\x18\x0b \x01(\x01\x12\x0c\n\x04velY\x18\x0c \x01(\x01\x12\x0c\n\x04velZ\x18\r \x01(\x01\x12\x14\n\x0cwholeSeconds\x18\x0e \x01(\x01\x12\x19\n\x11\x66ractionalSeconds\x18\x0f \x01(\x01\x12\x16\n\x0b\x66rameLength\x18\x10 \x01(\x05:\x01\x30\x12\r\n\x05\x66rame\x18\x11 \x01(\x0c\x12\x0c\n\x04uuid\x18\x12 \x01(\tB\x18\n\x0c\x66v.pm.protosB\x08PMProtos')




_PMFRAME = _descriptor.Descriptor(
  name='PMFrame',
  full_name='fv.tb.protos.PMProtos.PMFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='fv.tb.protos.PMProtos.PMFrame.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("PMFRAME", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toAddress', full_name='fv.tb.protos.PMProtos.PMFrame.toAddress', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fromAddress', full_name='fv.tb.protos.PMProtos.PMFrame.fromAddress', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='countValue', full_name='fv.tb.protos.PMProtos.PMFrame.countValue', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frameFormatID', full_name='fv.tb.protos.PMProtos.PMFrame.frameFormatID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackID', full_name='fv.tb.protos.PMProtos.PMFrame.trackID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackType', full_name='fv.tb.protos.PMProtos.PMFrame.trackType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posX', full_name='fv.tb.protos.PMProtos.PMFrame.posX', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posY', full_name='fv.tb.protos.PMProtos.PMFrame.posY', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posZ', full_name='fv.tb.protos.PMProtos.PMFrame.posZ', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velX', full_name='fv.tb.protos.PMProtos.PMFrame.velX', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velY', full_name='fv.tb.protos.PMProtos.PMFrame.velY', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velZ', full_name='fv.tb.protos.PMProtos.PMFrame.velZ', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wholeSeconds', full_name='fv.tb.protos.PMProtos.PMFrame.wholeSeconds', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fractionalSeconds', full_name='fv.tb.protos.PMProtos.PMFrame.fractionalSeconds', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frameLength', full_name='fv.tb.protos.PMProtos.PMFrame.frameLength', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame', full_name='fv.tb.protos.PMProtos.PMFrame.frame', index=16,
      number=17, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='fv.tb.protos.PMProtos.PMFrame.uuid', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=392,
)

DESCRIPTOR.message_types_by_name['PMFrame'] = _PMFRAME

class PMFrame(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PMFRAME

  # @@protoc_insertion_point(class_scope:fv.tb.protos.PMProtos.PMFrame)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\014fv.pm.protosB\010PMProtos')
# @@protoc_insertion_point(module_scope)
