# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateKeeperMessages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StateKeeperMessages.proto',
  package='raptorx_msg',
  serialized_pb='\n\x19StateKeeperMessages.proto\x12\x0braptorx_msg\"K\n\x11StateKeeperStatus\x12\"\n\x07msgName\x18\x01 \x01(\t:\x11StateKeeperStatus\x12\x12\n\nstate_name\x18\x02 \x01(\t\"\xbe\x02\n\tDetection\x12\x1a\n\x07msgName\x18\x01 \x01(\t:\tDetection\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x1b\n\x13\x63haracterization_id\x18\x03 \x01(\x03\x12\x0e\n\x06signal\x18\x04 \x01(\t\x12\x0c\n\x04\x66\x65\x65\x64\x18\x05 \x01(\t\x12\x12\n\ntime_whole\x18\x06 \x01(\x03\x12\x17\n\x0ftime_fractional\x18\x07 \x01(\x01\x12\x10\n\x08\x64uration\x18\x08 \x01(\x01\x12\x18\n\x10\x63\x65nter_frequency\x18\t \x01(\x01\x12\x11\n\tbandwidth\x18\n \x01(\x01\x12\x0f\n\x07\x61zimuth\x18\x0b \x01(\x01\x12\x11\n\televation\x18\x0c \x01(\x01\x12\x0b\n\x03snr\x18\r \x01(\x01\x12\x0e\n\x06hidden\x18\x0e \x01(\x08\x12\x0f\n\x07wrindex\x18\x0f \x01(\x05\x12\x10\n\x08globalID\x18\x10 \x01(\t\"\x9f\x01\n\x11SensorGPSPosition\x12\"\n\x07msgName\x18\x01 \x01(\t:\x11SensorGPSPosition\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lon\x18\x03 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x04 \x01(\x02\x12\r\n\x05major\x18\x05 \x01(\x02\x12\r\n\x05minor\x18\x06 \x01(\x02\x12\x0e\n\x06vector\x18\x07 \x01(\x02\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"\xa0\x01\n\x0c\x41\x63tionStatus\x12\x1d\n\x07msgName\x18\x01 \x01(\t:\x0c\x41\x63tionStatus\x12\x11\n\texecuting\x18\x02 \x01(\t\x12\r\n\x05\x61mpOn\x18\x03 \x01(\t\x12\x18\n\x10strikeAssessment\x18\x04 \x01(\t\x12\x13\n\x0bunderAttack\x18\x05 \x01(\t\x12\x0f\n\x07jamType\x18\x06 \x01(\t\x12\x0f\n\x07jamFreq\x18\x07 \x01(\x02\"q\n\x0cSystemStatus\x12\x1d\n\x07msgName\x18\x01 \x01(\t:\x0cSystemStatus\x12\x17\n\x0fhardware_status\x18\x02 \x01(\t\x12\x17\n\x0fsoftware_status\x18\x03 \x01(\t\x12\x10\n\x08gps_lock\x18\x04 \x01(\t\"\x1d\n\x04Ping\x12\x15\n\x07msgName\x18\x01 \x01(\t:\x04PingB\x15\n\x13\x66v.protos.kepsvisor')




_STATEKEEPERSTATUS = _descriptor.Descriptor(
  name='StateKeeperStatus',
  full_name='raptorx_msg.StateKeeperStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='raptorx_msg.StateKeeperStatus.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("StateKeeperStatus", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_name', full_name='raptorx_msg.StateKeeperStatus.state_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=117,
)


_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='raptorx_msg.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='raptorx_msg.Detection.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("Detection", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='raptorx_msg.Detection.id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='characterization_id', full_name='raptorx_msg.Detection.characterization_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal', full_name='raptorx_msg.Detection.signal', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feed', full_name='raptorx_msg.Detection.feed', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_whole', full_name='raptorx_msg.Detection.time_whole', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_fractional', full_name='raptorx_msg.Detection.time_fractional', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='raptorx_msg.Detection.duration', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='center_frequency', full_name='raptorx_msg.Detection.center_frequency', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='raptorx_msg.Detection.bandwidth', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='azimuth', full_name='raptorx_msg.Detection.azimuth', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='raptorx_msg.Detection.elevation', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='snr', full_name='raptorx_msg.Detection.snr', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden', full_name='raptorx_msg.Detection.hidden', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrindex', full_name='raptorx_msg.Detection.wrindex', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='globalID', full_name='raptorx_msg.Detection.globalID', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=120,
  serialized_end=438,
)


_SENSORGPSPOSITION = _descriptor.Descriptor(
  name='SensorGPSPosition',
  full_name='raptorx_msg.SensorGPSPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='raptorx_msg.SensorGPSPosition.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("SensorGPSPosition", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='raptorx_msg.SensorGPSPosition.lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='raptorx_msg.SensorGPSPosition.lon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alt', full_name='raptorx_msg.SensorGPSPosition.alt', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='major', full_name='raptorx_msg.SensorGPSPosition.major', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='raptorx_msg.SensorGPSPosition.minor', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vector', full_name='raptorx_msg.SensorGPSPosition.vector', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='raptorx_msg.SensorGPSPosition.timestamp', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=441,
  serialized_end=600,
)


_ACTIONSTATUS = _descriptor.Descriptor(
  name='ActionStatus',
  full_name='raptorx_msg.ActionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='raptorx_msg.ActionStatus.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("ActionStatus", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executing', full_name='raptorx_msg.ActionStatus.executing', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ampOn', full_name='raptorx_msg.ActionStatus.ampOn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strikeAssessment', full_name='raptorx_msg.ActionStatus.strikeAssessment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='underAttack', full_name='raptorx_msg.ActionStatus.underAttack', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jamType', full_name='raptorx_msg.ActionStatus.jamType', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jamFreq', full_name='raptorx_msg.ActionStatus.jamFreq', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=603,
  serialized_end=763,
)


_SYSTEMSTATUS = _descriptor.Descriptor(
  name='SystemStatus',
  full_name='raptorx_msg.SystemStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='raptorx_msg.SystemStatus.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("SystemStatus", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware_status', full_name='raptorx_msg.SystemStatus.hardware_status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='software_status', full_name='raptorx_msg.SystemStatus.software_status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_lock', full_name='raptorx_msg.SystemStatus.gps_lock', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=765,
  serialized_end=878,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='raptorx_msg.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgName', full_name='raptorx_msg.Ping.msgName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("Ping", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=880,
  serialized_end=909,
)

DESCRIPTOR.message_types_by_name['StateKeeperStatus'] = _STATEKEEPERSTATUS
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['SensorGPSPosition'] = _SENSORGPSPOSITION
DESCRIPTOR.message_types_by_name['ActionStatus'] = _ACTIONSTATUS
DESCRIPTOR.message_types_by_name['SystemStatus'] = _SYSTEMSTATUS
DESCRIPTOR.message_types_by_name['Ping'] = _PING

class StateKeeperStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATEKEEPERSTATUS

  # @@protoc_insertion_point(class_scope:raptorx_msg.StateKeeperStatus)

class Detection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DETECTION

  # @@protoc_insertion_point(class_scope:raptorx_msg.Detection)

class SensorGPSPosition(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENSORGPSPOSITION

  # @@protoc_insertion_point(class_scope:raptorx_msg.SensorGPSPosition)

class ActionStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIONSTATUS

  # @@protoc_insertion_point(class_scope:raptorx_msg.ActionStatus)

class SystemStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYSTEMSTATUS

  # @@protoc_insertion_point(class_scope:raptorx_msg.SystemStatus)

class Ping(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PING

  # @@protoc_insertion_point(class_scope:raptorx_msg.Ping)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023fv.protos.kepsvisor')
# @@protoc_insertion_point(module_scope)
