// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_cotexporter.proto

package fv.protos.kepsvisor;

public final class ServiceCotexporter {
  private ServiceCotexporter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface COTExporterConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];
    /**
     * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
     */
    boolean hasMsgName();
    /**
     * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
     */
    java.lang.String getMsgName();
    /**
     * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
     */
    com.google.protobuf.ByteString
        getMsgNameBytes();

    // optional string exportProtocol = 2 [default = "UDP"];
    /**
     * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
     *
     * <pre>
     * Protocol to use for export. Currently only UDP is supported.
     * </pre>
     */
    boolean hasExportProtocol();
    /**
     * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
     *
     * <pre>
     * Protocol to use for export. Currently only UDP is supported.
     * </pre>
     */
    java.lang.String getExportProtocol();
    /**
     * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
     *
     * <pre>
     * Protocol to use for export. Currently only UDP is supported.
     * </pre>
     */
    com.google.protobuf.ByteString
        getExportProtocolBytes();

    // optional string ipAddr = 3 [default = "239.1.1.1"];
    /**
     * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
     *
     * <pre>
     * Export IP Address
     * </pre>
     */
    boolean hasIpAddr();
    /**
     * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
     *
     * <pre>
     * Export IP Address
     * </pre>
     */
    java.lang.String getIpAddr();
    /**
     * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
     *
     * <pre>
     * Export IP Address
     * </pre>
     */
    com.google.protobuf.ByteString
        getIpAddrBytes();

    // optional int32 exportPort = 4 [default = 9500];
    /**
     * <code>optional int32 exportPort = 4 [default = 9500];</code>
     *
     * <pre>
     * Export Port
     * </pre>
     */
    boolean hasExportPort();
    /**
     * <code>optional int32 exportPort = 4 [default = 9500];</code>
     *
     * <pre>
     * Export Port
     * </pre>
     */
    int getExportPort();
  }
  /**
   * Protobuf type {@code service_cotexporter.COTExporterConfig}
   */
  public static final class COTExporterConfig extends
      com.google.protobuf.GeneratedMessage
      implements COTExporterConfigOrBuilder {
    // Use COTExporterConfig.newBuilder() to construct.
    private COTExporterConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private COTExporterConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final COTExporterConfig defaultInstance;
    public static COTExporterConfig getDefaultInstance() {
      return defaultInstance;
    }

    public COTExporterConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private COTExporterConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msgName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              exportProtocol_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              ipAddr_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              exportPort_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fv.protos.kepsvisor.ServiceCotexporter.internal_static_service_cotexporter_COTExporterConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fv.protos.kepsvisor.ServiceCotexporter.internal_static_service_cotexporter_COTExporterConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig.class, fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<COTExporterConfig> PARSER =
        new com.google.protobuf.AbstractParser<COTExporterConfig>() {
      public COTExporterConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new COTExporterConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<COTExporterConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];
    public static final int MSGNAME_FIELD_NUMBER = 1;
    private java.lang.Object msgName_;
    /**
     * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
     */
    public boolean hasMsgName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
     */
    public java.lang.String getMsgName() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
     */
    public com.google.protobuf.ByteString
        getMsgNameBytes() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string exportProtocol = 2 [default = "UDP"];
    public static final int EXPORTPROTOCOL_FIELD_NUMBER = 2;
    private java.lang.Object exportProtocol_;
    /**
     * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
     *
     * <pre>
     * Protocol to use for export. Currently only UDP is supported.
     * </pre>
     */
    public boolean hasExportProtocol() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
     *
     * <pre>
     * Protocol to use for export. Currently only UDP is supported.
     * </pre>
     */
    public java.lang.String getExportProtocol() {
      java.lang.Object ref = exportProtocol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exportProtocol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
     *
     * <pre>
     * Protocol to use for export. Currently only UDP is supported.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getExportProtocolBytes() {
      java.lang.Object ref = exportProtocol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exportProtocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ipAddr = 3 [default = "239.1.1.1"];
    public static final int IPADDR_FIELD_NUMBER = 3;
    private java.lang.Object ipAddr_;
    /**
     * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
     *
     * <pre>
     * Export IP Address
     * </pre>
     */
    public boolean hasIpAddr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
     *
     * <pre>
     * Export IP Address
     * </pre>
     */
    public java.lang.String getIpAddr() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
     *
     * <pre>
     * Export IP Address
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIpAddrBytes() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 exportPort = 4 [default = 9500];
    public static final int EXPORTPORT_FIELD_NUMBER = 4;
    private int exportPort_;
    /**
     * <code>optional int32 exportPort = 4 [default = 9500];</code>
     *
     * <pre>
     * Export Port
     * </pre>
     */
    public boolean hasExportPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 exportPort = 4 [default = 9500];</code>
     *
     * <pre>
     * Export Port
     * </pre>
     */
    public int getExportPort() {
      return exportPort_;
    }

    private void initFields() {
      msgName_ = "service_cotexporter.COTExporterConfig";
      exportProtocol_ = "UDP";
      ipAddr_ = "239.1.1.1";
      exportPort_ = 9500;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getExportProtocolBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIpAddrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, exportPort_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getExportProtocolBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIpAddrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, exportPort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code service_cotexporter.COTExporterConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fv.protos.kepsvisor.ServiceCotexporter.internal_static_service_cotexporter_COTExporterConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fv.protos.kepsvisor.ServiceCotexporter.internal_static_service_cotexporter_COTExporterConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig.class, fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig.Builder.class);
      }

      // Construct using fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgName_ = "service_cotexporter.COTExporterConfig";
        bitField0_ = (bitField0_ & ~0x00000001);
        exportProtocol_ = "UDP";
        bitField0_ = (bitField0_ & ~0x00000002);
        ipAddr_ = "239.1.1.1";
        bitField0_ = (bitField0_ & ~0x00000004);
        exportPort_ = 9500;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fv.protos.kepsvisor.ServiceCotexporter.internal_static_service_cotexporter_COTExporterConfig_descriptor;
      }

      public fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig getDefaultInstanceForType() {
        return fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig.getDefaultInstance();
      }

      public fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig build() {
        fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig buildPartial() {
        fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig result = new fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgName_ = msgName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.exportProtocol_ = exportProtocol_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ipAddr_ = ipAddr_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.exportPort_ = exportPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig) {
          return mergeFrom((fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig other) {
        if (other == fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig.getDefaultInstance()) return this;
        if (other.hasMsgName()) {
          bitField0_ |= 0x00000001;
          msgName_ = other.msgName_;
          onChanged();
        }
        if (other.hasExportProtocol()) {
          bitField0_ |= 0x00000002;
          exportProtocol_ = other.exportProtocol_;
          onChanged();
        }
        if (other.hasIpAddr()) {
          bitField0_ |= 0x00000004;
          ipAddr_ = other.ipAddr_;
          onChanged();
        }
        if (other.hasExportPort()) {
          setExportPort(other.getExportPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fv.protos.kepsvisor.ServiceCotexporter.COTExporterConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];
      private java.lang.Object msgName_ = "service_cotexporter.COTExporterConfig";
      /**
       * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
       */
      public boolean hasMsgName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
       */
      public java.lang.String getMsgName() {
        java.lang.Object ref = msgName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
       */
      public com.google.protobuf.ByteString
          getMsgNameBytes() {
        java.lang.Object ref = msgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
       */
      public Builder setMsgName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
       */
      public Builder clearMsgName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgName_ = getDefaultInstance().getMsgName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgName = 1 [default = "service_cotexporter.COTExporterConfig"];</code>
       */
      public Builder setMsgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgName_ = value;
        onChanged();
        return this;
      }

      // optional string exportProtocol = 2 [default = "UDP"];
      private java.lang.Object exportProtocol_ = "UDP";
      /**
       * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
       *
       * <pre>
       * Protocol to use for export. Currently only UDP is supported.
       * </pre>
       */
      public boolean hasExportProtocol() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
       *
       * <pre>
       * Protocol to use for export. Currently only UDP is supported.
       * </pre>
       */
      public java.lang.String getExportProtocol() {
        java.lang.Object ref = exportProtocol_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          exportProtocol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
       *
       * <pre>
       * Protocol to use for export. Currently only UDP is supported.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getExportProtocolBytes() {
        java.lang.Object ref = exportProtocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exportProtocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
       *
       * <pre>
       * Protocol to use for export. Currently only UDP is supported.
       * </pre>
       */
      public Builder setExportProtocol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exportProtocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
       *
       * <pre>
       * Protocol to use for export. Currently only UDP is supported.
       * </pre>
       */
      public Builder clearExportProtocol() {
        bitField0_ = (bitField0_ & ~0x00000002);
        exportProtocol_ = getDefaultInstance().getExportProtocol();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exportProtocol = 2 [default = "UDP"];</code>
       *
       * <pre>
       * Protocol to use for export. Currently only UDP is supported.
       * </pre>
       */
      public Builder setExportProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exportProtocol_ = value;
        onChanged();
        return this;
      }

      // optional string ipAddr = 3 [default = "239.1.1.1"];
      private java.lang.Object ipAddr_ = "239.1.1.1";
      /**
       * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
       *
       * <pre>
       * Export IP Address
       * </pre>
       */
      public boolean hasIpAddr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
       *
       * <pre>
       * Export IP Address
       * </pre>
       */
      public java.lang.String getIpAddr() {
        java.lang.Object ref = ipAddr_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ipAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
       *
       * <pre>
       * Export IP Address
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIpAddrBytes() {
        java.lang.Object ref = ipAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
       *
       * <pre>
       * Export IP Address
       * </pre>
       */
      public Builder setIpAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ipAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
       *
       * <pre>
       * Export IP Address
       * </pre>
       */
      public Builder clearIpAddr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ipAddr_ = getDefaultInstance().getIpAddr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ipAddr = 3 [default = "239.1.1.1"];</code>
       *
       * <pre>
       * Export IP Address
       * </pre>
       */
      public Builder setIpAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ipAddr_ = value;
        onChanged();
        return this;
      }

      // optional int32 exportPort = 4 [default = 9500];
      private int exportPort_ = 9500;
      /**
       * <code>optional int32 exportPort = 4 [default = 9500];</code>
       *
       * <pre>
       * Export Port
       * </pre>
       */
      public boolean hasExportPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 exportPort = 4 [default = 9500];</code>
       *
       * <pre>
       * Export Port
       * </pre>
       */
      public int getExportPort() {
        return exportPort_;
      }
      /**
       * <code>optional int32 exportPort = 4 [default = 9500];</code>
       *
       * <pre>
       * Export Port
       * </pre>
       */
      public Builder setExportPort(int value) {
        bitField0_ |= 0x00000008;
        exportPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exportPort = 4 [default = 9500];</code>
       *
       * <pre>
       * Export Port
       * </pre>
       */
      public Builder clearExportPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        exportPort_ = 9500;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:service_cotexporter.COTExporterConfig)
    }

    static {
      defaultInstance = new COTExporterConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:service_cotexporter.COTExporterConfig)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_service_cotexporter_COTExporterConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_cotexporter_COTExporterConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031service_cotexporter.proto\022\023service_cot" +
      "exporter\"\235\001\n\021COTExporterConfig\0226\n\007msgNam" +
      "e\030\001 \001(\t:%service_cotexporter.COTExporter" +
      "Config\022\033\n\016exportProtocol\030\002 \001(\t:\003UDP\022\031\n\006i" +
      "pAddr\030\003 \001(\t:\t239.1.1.1\022\030\n\nexportPort\030\004 \001" +
      "(\005:\0049500B\025\n\023fv.protos.kepsvisor"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_service_cotexporter_COTExporterConfig_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_service_cotexporter_COTExporterConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_service_cotexporter_COTExporterConfig_descriptor,
              new java.lang.String[] { "MsgName", "ExportProtocol", "IpAddr", "ExportPort", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
