// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RxControlTopic.proto

#ifndef PROTOBUF_RxControlTopic_2eproto__INCLUDED
#define PROTOBUF_RxControlTopic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rx_msg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RxControlTopic_2eproto();
void protobuf_AssignDesc_RxControlTopic_2eproto();
void protobuf_ShutdownFile_RxControlTopic_2eproto();

class ReceiverRequest;
class ReceiverRelease;
class ReceiverAcquired;
class ReceiverReleased;

// ===================================================================

class ReceiverRequest : public ::google::protobuf::Message {
 public:
  ReceiverRequest();
  virtual ~ReceiverRequest();

  ReceiverRequest(const ReceiverRequest& from);

  inline ReceiverRequest& operator=(const ReceiverRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReceiverRequest& default_instance();

  void Swap(ReceiverRequest* other);

  // implements Message ----------------------------------------------

  ReceiverRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReceiverRequest& from);
  void MergeFrom(const ReceiverRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 appID = 1;
  inline bool has_appid() const;
  inline void clear_appid();
  static const int kAppIDFieldNumber = 1;
  inline ::google::protobuf::int32 appid() const;
  inline void set_appid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rx_msg.ReceiverRequest)
 private:
  inline void set_has_appid();
  inline void clear_has_appid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 appid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_RxControlTopic_2eproto();
  friend void protobuf_AssignDesc_RxControlTopic_2eproto();
  friend void protobuf_ShutdownFile_RxControlTopic_2eproto();

  void InitAsDefaultInstance();
  static ReceiverRequest* default_instance_;
};
// -------------------------------------------------------------------

class ReceiverRelease : public ::google::protobuf::Message {
 public:
  ReceiverRelease();
  virtual ~ReceiverRelease();

  ReceiverRelease(const ReceiverRelease& from);

  inline ReceiverRelease& operator=(const ReceiverRelease& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReceiverRelease& default_instance();

  void Swap(ReceiverRelease* other);

  // implements Message ----------------------------------------------

  ReceiverRelease* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReceiverRelease& from);
  void MergeFrom(const ReceiverRelease& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 appID = 1;
  inline bool has_appid() const;
  inline void clear_appid();
  static const int kAppIDFieldNumber = 1;
  inline ::google::protobuf::int32 appid() const;
  inline void set_appid(::google::protobuf::int32 value);

  // optional int32 channel = 2;
  inline bool has_channel() const;
  inline void clear_channel();
  static const int kChannelFieldNumber = 2;
  inline ::google::protobuf::int32 channel() const;
  inline void set_channel(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rx_msg.ReceiverRelease)
 private:
  inline void set_has_appid();
  inline void clear_has_appid();
  inline void set_has_channel();
  inline void clear_has_channel();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 appid_;
  ::google::protobuf::int32 channel_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_RxControlTopic_2eproto();
  friend void protobuf_AssignDesc_RxControlTopic_2eproto();
  friend void protobuf_ShutdownFile_RxControlTopic_2eproto();

  void InitAsDefaultInstance();
  static ReceiverRelease* default_instance_;
};
// -------------------------------------------------------------------

class ReceiverAcquired : public ::google::protobuf::Message {
 public:
  ReceiverAcquired();
  virtual ~ReceiverAcquired();

  ReceiverAcquired(const ReceiverAcquired& from);

  inline ReceiverAcquired& operator=(const ReceiverAcquired& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReceiverAcquired& default_instance();

  void Swap(ReceiverAcquired* other);

  // implements Message ----------------------------------------------

  ReceiverAcquired* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReceiverAcquired& from);
  void MergeFrom(const ReceiverAcquired& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 appID = 1;
  inline bool has_appid() const;
  inline void clear_appid();
  static const int kAppIDFieldNumber = 1;
  inline ::google::protobuf::int32 appid() const;
  inline void set_appid(::google::protobuf::int32 value);

  // optional int32 channel = 2;
  inline bool has_channel() const;
  inline void clear_channel();
  static const int kChannelFieldNumber = 2;
  inline ::google::protobuf::int32 channel() const;
  inline void set_channel(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rx_msg.ReceiverAcquired)
 private:
  inline void set_has_appid();
  inline void clear_has_appid();
  inline void set_has_channel();
  inline void clear_has_channel();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 appid_;
  ::google::protobuf::int32 channel_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_RxControlTopic_2eproto();
  friend void protobuf_AssignDesc_RxControlTopic_2eproto();
  friend void protobuf_ShutdownFile_RxControlTopic_2eproto();

  void InitAsDefaultInstance();
  static ReceiverAcquired* default_instance_;
};
// -------------------------------------------------------------------

class ReceiverReleased : public ::google::protobuf::Message {
 public:
  ReceiverReleased();
  virtual ~ReceiverReleased();

  ReceiverReleased(const ReceiverReleased& from);

  inline ReceiverReleased& operator=(const ReceiverReleased& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReceiverReleased& default_instance();

  void Swap(ReceiverReleased* other);

  // implements Message ----------------------------------------------

  ReceiverReleased* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReceiverReleased& from);
  void MergeFrom(const ReceiverReleased& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 appID = 1;
  inline bool has_appid() const;
  inline void clear_appid();
  static const int kAppIDFieldNumber = 1;
  inline ::google::protobuf::int32 appid() const;
  inline void set_appid(::google::protobuf::int32 value);

  // optional int32 channel = 2;
  inline bool has_channel() const;
  inline void clear_channel();
  static const int kChannelFieldNumber = 2;
  inline ::google::protobuf::int32 channel() const;
  inline void set_channel(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rx_msg.ReceiverReleased)
 private:
  inline void set_has_appid();
  inline void clear_has_appid();
  inline void set_has_channel();
  inline void clear_has_channel();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 appid_;
  ::google::protobuf::int32 channel_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_RxControlTopic_2eproto();
  friend void protobuf_AssignDesc_RxControlTopic_2eproto();
  friend void protobuf_ShutdownFile_RxControlTopic_2eproto();

  void InitAsDefaultInstance();
  static ReceiverReleased* default_instance_;
};
// ===================================================================


// ===================================================================

// ReceiverRequest

// optional int32 appID = 1;
inline bool ReceiverRequest::has_appid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReceiverRequest::set_has_appid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReceiverRequest::clear_has_appid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReceiverRequest::clear_appid() {
  appid_ = 0;
  clear_has_appid();
}
inline ::google::protobuf::int32 ReceiverRequest::appid() const {
  return appid_;
}
inline void ReceiverRequest::set_appid(::google::protobuf::int32 value) {
  set_has_appid();
  appid_ = value;
}

// -------------------------------------------------------------------

// ReceiverRelease

// optional int32 appID = 1;
inline bool ReceiverRelease::has_appid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReceiverRelease::set_has_appid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReceiverRelease::clear_has_appid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReceiverRelease::clear_appid() {
  appid_ = 0;
  clear_has_appid();
}
inline ::google::protobuf::int32 ReceiverRelease::appid() const {
  return appid_;
}
inline void ReceiverRelease::set_appid(::google::protobuf::int32 value) {
  set_has_appid();
  appid_ = value;
}

// optional int32 channel = 2;
inline bool ReceiverRelease::has_channel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReceiverRelease::set_has_channel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReceiverRelease::clear_has_channel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReceiverRelease::clear_channel() {
  channel_ = 0;
  clear_has_channel();
}
inline ::google::protobuf::int32 ReceiverRelease::channel() const {
  return channel_;
}
inline void ReceiverRelease::set_channel(::google::protobuf::int32 value) {
  set_has_channel();
  channel_ = value;
}

// -------------------------------------------------------------------

// ReceiverAcquired

// optional int32 appID = 1;
inline bool ReceiverAcquired::has_appid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReceiverAcquired::set_has_appid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReceiverAcquired::clear_has_appid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReceiverAcquired::clear_appid() {
  appid_ = 0;
  clear_has_appid();
}
inline ::google::protobuf::int32 ReceiverAcquired::appid() const {
  return appid_;
}
inline void ReceiverAcquired::set_appid(::google::protobuf::int32 value) {
  set_has_appid();
  appid_ = value;
}

// optional int32 channel = 2;
inline bool ReceiverAcquired::has_channel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReceiverAcquired::set_has_channel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReceiverAcquired::clear_has_channel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReceiverAcquired::clear_channel() {
  channel_ = 0;
  clear_has_channel();
}
inline ::google::protobuf::int32 ReceiverAcquired::channel() const {
  return channel_;
}
inline void ReceiverAcquired::set_channel(::google::protobuf::int32 value) {
  set_has_channel();
  channel_ = value;
}

// -------------------------------------------------------------------

// ReceiverReleased

// optional int32 appID = 1;
inline bool ReceiverReleased::has_appid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReceiverReleased::set_has_appid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReceiverReleased::clear_has_appid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReceiverReleased::clear_appid() {
  appid_ = 0;
  clear_has_appid();
}
inline ::google::protobuf::int32 ReceiverReleased::appid() const {
  return appid_;
}
inline void ReceiverReleased::set_appid(::google::protobuf::int32 value) {
  set_has_appid();
  appid_ = value;
}

// optional int32 channel = 2;
inline bool ReceiverReleased::has_channel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReceiverReleased::set_has_channel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReceiverReleased::clear_has_channel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReceiverReleased::clear_channel() {
  channel_ = 0;
  clear_has_channel();
}
inline ::google::protobuf::int32 ReceiverReleased::channel() const {
  return channel_;
}
inline void ReceiverReleased::set_channel(::google::protobuf::int32 value) {
  set_has_channel();
  channel_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rx_msg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RxControlTopic_2eproto__INCLUDED
