// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatusCommon.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "StatusCommon.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace srcinc {
namespace ngi {
namespace data {

namespace {

const ::google::protobuf::EnumDescriptor* Status_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_StatusCommon_2eproto() {
  protobuf_AddDesc_StatusCommon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "StatusCommon.proto");
  GOOGLE_CHECK(file != NULL);
  Status_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_StatusCommon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_StatusCommon_2eproto() {
}

void protobuf_AddDesc_StatusCommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022StatusCommon.proto\022\023com.srcinc.ngi.dat"
    "a*s\n\006Status\022\031\n\025STATUS_NOT_APPLICABLE\020\000\022\022"
    "\n\016STATUS_UNKNOWN\020\001\022\021\n\rSTATUS_NORMAL\020\002\022\023\n"
    "\017STATUS_DEGRADED\020\003\022\022\n\016STATUS_FAULTED\020\004", 158);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "StatusCommon.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_StatusCommon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_StatusCommon_2eproto {
  StaticDescriptorInitializer_StatusCommon_2eproto() {
    protobuf_AddDesc_StatusCommon_2eproto();
  }
} static_descriptor_initializer_StatusCommon_2eproto_;
const ::google::protobuf::EnumDescriptor* Status_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Status_descriptor_;
}
bool Status_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace ngi
}  // namespace srcinc
}  // namespace com

// @@protoc_insertion_point(global_scope)
